# Generated by Django 3.2.4 on 2021-06-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50, verbose_name='Artist')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('producer', models.CharField(max_length=50, verbose_name='Producer')),
                ('studio', models.CharField(max_length=50, verbose_name='Studio')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('length', models.DurationField(verbose_name='Length')),
                ('track_format', models.CharField(max_length=50, verbose_name='Format')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
            ],
        ),
    ]
