# Generated by Django 3.2.4 on 2021-06-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='studio',
        ),
    ]
